apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: migration-planner
spec:
  selector:
    matchLabels:
      app: migration-planner
  replicas: 1
  template:
    metadata:
      labels:
        app: migration-planner
    spec:
      containers:
        - name: migration-planner
          resources:
            limits:
              cpu: 500m
              memory: 2000Mi
            requests:
              cpu: 300m
              memory: 400Mi
          image: quay.io/kubev2v/migration-planner-api
          imagePullPolicy: Always
          ports:
            - containerPort: 3443
          livenessProbe:
            httpGet:
              path: /health
              port: 3443
            initialDelaySeconds: 30
          env:
            - name: CONFIG_SERVER
              valueFrom:
                secretKeyRef:
                  name: migration-planner-secret
                  key: config_server
            - name: CONFIG_SERVER_UI
              valueFrom:
                secretKeyRef:
                  name: migration-planner-secret
                  key: config_server_ui
            - name: MIGRATION_PLANNER_AGENT_IMAGE
              value: quay.io/kubev2v/migration-planner-agent
            - name:  INSECURE_REGISTRY
              value: "true"
          volumeMounts:
          volumeMounts:
            - name: migration-planner-config
              mountPath: "/.migration-planner/config.yaml"
              subPath: config.yaml
              readOnly: true
      serviceAccountName: migration-planner
      volumes:
        - name: migration-planner-config
          secret:
            secretName: migration-planner-rds
            optional: true
            items:
              - key: config.yaml
                path: config.yaml
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: migration-planner
